### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by chadbrewbaker** [jorgebastida/gordon#4]
I pulled the recommended Docker image down with Kitematic and it booted with the following error.
Kind of important for my workflow since I compile a lot of C code for Lambda, but feel free to close if you think this out of scope. 

{"errorMessage":"Cannot find module 'index'","errorType":"Error","stackTrace":["Function.Module._load (module.js:276:25)","Module.require (module.js:353:17)","require (internal/module.js:12:17)"]}
START RequestId: 87511eb4-1ea8-15aa-9a36-d93f338f827e Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
END RequestId: 87511eb4-1ea8-15aa-9a36-d93f338f827e
REPORT RequestId: 87511eb4-1ea8-15aa-9a36-d93f338f827e	Duration: 14.25 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 24 MB

**Comment by jorgebastida** [comment]
I'm not an expert in Docker, but this might be an issue with https://github.com/lambci/docker-lambda and not gordon?
