### ISSUE TITLE
S3 bucket cannot be ref://

### ISSUE THREAD

**Issue by tjsail33** [jorgebastida/gordon#57]
When trying to do 
```
s3:
  upload_lambda_trigger:
    bucket: ref://InputBucket
```
Gordon fails with 
```
Building project...
  0001_p.json
      cp -Rf * /Users/tcosta/.gordon/tmpIxTWCd
      pip install --install-option="--prefix=" -r requirements.txt -q -t /Users/tcosta/.gordon/tmpIxTWCd
      /Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
        cmdoptions.check_install_build_global(options)

      cd /Users/tcosta/.gordon/tmpIxTWCd && find . -name "*.pyc" -delete
      cp -Rf * /Users/tcosta/.gordon/tmpWuqh_1
      pip install --install-option="--prefix=" -r requirements.txt -q -t /Users/tcosta/.gordon/tmpWuqh_1
      /Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
        cmdoptions.check_install_build_global(options)

      cd /Users/tcosta/.gordon/tmpWuqh_1 && find . -name "*.pyc" -delete
      cp -Rf * /Users/tcosta/.gordon/tmpViyHe0
      cp -Rf * /Users/tcosta/.gordon/tmpJovOg2
  0002_pr_r.json
Traceback (most recent call last):
  File "/usr/local/bin/gordon", line 9, in <module>
    load_entry_point('gordon==0.2.1', 'console_scripts', 'gordon')()
  File "/Library/Python/2.7/site-packages/gordon/bin.py", line 106, in main
    getattr(obj, options.func)()
  File "/Library/Python/2.7/site-packages/gordon/core.py", line 243, in build
    self._build_resources_template()
  File "/Library/Python/2.7/site-packages/gordon/core.py", line 334, in _build_resources_template
    r.register_resources_template(template)
  File "/Library/Python/2.7/site-packages/gordon/resources/s3.py", line 337, in register_resources_template
    Bucket=self.get_bucket_name(),
  File "/Library/Python/2.7/site-packages/gordon/resources/s3.py", line 274, in get_bucket_name
    if bucket.startswith('arn:aws:'):
AttributeError: 'Ref' object has no attribute 'startswith'
```

This is with debug mode on. The ref is defined in `dev.yml` as
```
---
InputBucket: my-test-bucket
```

The build succeeds if the ref is used in the context property and the ref is removed from the s3 key.

**Comment by camfraser** [comment]
👍 
https://github.com/jorgebastida/gordon/blob/08dde632f0eb9bfa11d2437f690de3b6a7f8d2d0/examples/s3/settings.yml#L14

This should be able to be a `ref://` that is defined in a common.yml file

**Comment by shin-nien** [comment]
I'm blocked by this too.

Wondering if it worked at some point because the documentation seems to suggest so:

https://gordon.readthedocs.io/en/latest/parameters.html#how-can-i-use-parameters

**Comment by tjbaker** [comment]
Bit by this as well.

**Comment by tjsail33** [comment]
@shin-nien @tjbaker I have published `gordon-alt` at https://pypi.python.org/pypi/gordon-alt/0.2.2. It contains a fix for this issue.
